spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: alice
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secrets: secreto